/**
 * Conteúdo do Quiz Arena.
 *
 * Pelo fluxograma, o documento de alternativas guarda **somente alternativas
 * corretas** — não existe distrator. O jogador digita a resposta por extenso e
 * o backend faz o *word match*, ignorando caixa e acentos, para descobrir qual
 * das formas aceitas ele usou.
 *
 * Como toda alternativa vale ponto, as perguntas são abertas: existem muitas
 * respostas igualmente válidas para a mesma pergunta, e a pontuação é por
 * raridade. A resposta que menos gente usou é a que mais rende.
 */

export type QuestaoSeed = {
  slug: string
  enunciado: string
  categoria: string
  /** Formas aceitas de resposta. Todas valem ponto. */
  alternativas: string[]
}

export type DisciplinaSeed = {
  slug: string
  nome: string
  descricao: string
  questoes: QuestaoSeed[]
}

export const TEMAS_SEED = [
  {
    slug: 'tema-arte-cultura',
    titulo: 'Arte & Cultura',
    descricao: 'Movimentos, obras e Instrumentos que atravessaram séculos.',
    data: '2026-09-29',
    tom: 'coral',
  },
  {
    slug: 'tema-corpo-e-natureza',
    titulo: 'Corpo & Natureza',
    descricao: 'Biologia e Química, sem complicação.',
    data: '2026-09-22',
    tom: 'green',
  },
  {
    slug: 'tema-numeros-e-texto',
    titulo: 'Números & Texto',
    descricao: 'Matemática, Português e Inglês.',
    data: '2026-09-15',
    tom: 'amber',
  },
  {
    slug: 'tema-origens',
    titulo: 'História & Física',
    descricao: 'De onde viemos e como o mundo funciona.',
    data: '2026-09-08',
    tom: 'blue',
  },
] as const

export const DISCIPLINAS_SEED: DisciplinaSeed[] = [
  {
    slug: 'artes',
    nome: 'Artes',
    descricao: 'Movimentos artísticos, obras, autores e técnicas.',
    questoes: [
      {
        slug: 'movimento-artistico',
        enunciado: 'Qual é o nome de um movimento artístico?',
        categoria: 'Movimentos',
        alternativas: [
          'Impressionismo', 'Expressionismo', 'Cubismo', 'Surrealismo',
          'Romantismo', 'Barroco', 'Rococó', 'Neoclassicismo', 'Dadaísmo',
          'Construtivismo', 'Concretismo', 'Neoconcretismo', 'Abstracionismo',
          'Minimalismo', 'Pop art', 'Graffiti', 'Tropicalismo', 'Futurismo',
          'Simbolismo', 'Naturalismo', 'Realismo', 'Renascimento', 'Gótico',
          'Art déco', 'Art nouveau', 'Suprematismo', 'Fauvismo', 'Maneirismo',
          'Barroco tardio', 'Pós-impressionismo', 'Expressionismo abstrato',
          'Pontilhismo', 'Divisionismo', 'Modernismo', 'Tenebrismo',
        ],
      },
      {
        slug: 'obra-de-leonardo',
        enunciado: 'Qual é o título de uma obra de Leonardo da Vinci?',
        categoria: 'Pintura',
        alternativas: [
          'Mona Lisa', 'A Monalisa', 'La Gioconda', 'A Última Ceia',
          'Santa Ana', 'Virgem dos Rochedos', 'A Virgem dos Rochedos',
          'Salvator Mundi', 'A Dama de Ferrara', 'Benvenuto Cellini',
          'Estudo de mãos', 'Bela Principessa', 'Madonna Litta',
          'Gioconda', 'Senhora do Carnê', 'Homem Vitruviano',
          'Adoração dos Magos', 'A Primavera', 'Retrato de Mona Lisa',
          'Ginevra de Benci', 'Baptismo de Cristo', 'Saint Jerome', 'Leda',
          'A Joconda', 'São Jerônimo', 'Batismo de Cristo',
        ],
      },
      {
        slug: 'tecnica-de-pintura',
        enunciado: 'Qual é o nome de uma técnica de pintura?',
        categoria: 'Técnicas',
        alternativas: [
          'Óleo', 'Aquarela', 'Pastel', 'Guache', 'Têmpera',
          'Encaústica', 'A fresco', 'Fresco', 'Pintura a seco', 'Mosaico',
          'Litografia', 'Serigrafia', 'Xilogravia', 'Gravura em metal',
          'Frottage', 'Batik', 'Decalque', 'Sumiê', 'Vitral',
          'Retábulo', 'Grisaille', 'Camada oleosa', 'Pintura miniatura',
          'Sumi-e',
          'Acrílica', 'Pintura a óleo',
        ],
      },
      {
        slug: 'instrumento-musical',
        enunciado: 'Qual é o nome de um instrumento musical?',
        categoria: 'Música',
        alternativas: [
          'Violino', 'Violoncelo', 'Flauta', 'Clarinete', 'Saxofone', 'Trompete', 'Piano', 'Harpa', 'Bateria', 'Pandeiro', 'Cavaquinho', 'Violão', 'Acordeão', 'Oboé', 'Fagote', 'Tuba', 'Sitar', 'Marimba', 'Berimbau', 'Ganzá', 'Ukulele', 'Bandolim', 'Agogô', 'Cuíca', 'Carraca', 'Triângulo', 'Xilofone', 'Guitarra',
          'Gaita', 'Órgão', 'Teclado', 'Cítara', 'Sanfona',
        ],
      },
      {
        slug: 'artista-brasileiro',
        enunciado: 'Qual é o nome de um artista plástico brasileiro?',
        categoria: 'História da arte',
        alternativas: [
          'Tarsila do Amaral', 'Cândido Portinari', 'Anita Malfatti',
          'Lasar Segall', 'Di Cavalcanti', 'Paulo Uilkier', 'Eliseu Visconti',
          'Victor Meirelles', 'Pedro Américo', 'Jean-Baptiste Debret',
          'Georgina de Albuquerque', 'Ernestina Ruben', 'Emiliano Di Cavalcanti',
          'Romero de Torres', 'Oscar Pereira da Silva', 'Hélio Oiticica',
          'Lygia Clark', 'Beatriz Milhazes', 'Vik Muniz', 'Anna Maria Maiolino',
          'Rubens Valentim', 'Grazyna Szapska', 'Antonio Gomide', 'José Pancetti',
          'Portinari', 'Tarsila', 'Malfatti', 'Segall', 'Oiticica', 'Milhazes', 'Muniz', 'Clark',
        ],
      },
    ],
  },
  {
    slug: 'biologia',
    nome: 'Biologia',
    descricao: 'Célula, genética, ecologia e corpo humano.',
    questoes: [
      {
        slug: 'organela-celular',
        enunciado: 'Qual é o nome de uma organela presente nas células?',
        categoria: 'Citologia',
        alternativas: [
          'Mitocôndria', 'Ribossomo', 'Núcleo', 'Complexo golgiense',
          'Lisossomo', 'Vacúolo', 'Centríolo', 'Peroxissomo', 'Cloroplasto',
          'Retículo endoplasmático', 'Aparelto de Golgi', 'Citoesqueleto',
          'Tilacoide', 'Grana', 'Estroma', 'Carióptipo', 'Centrómero',
          'Nucléolo', 'Cromatina', 'Plásmido', 'Ribossomo livre',
          'Membrana plasmática', 'Célula muscular', 'Vesícula',
          'Golgi', 'Ribossomos', 'Citosol',
        ],
      },
      {
        slug: 'animal-mamifero',
        enunciado: 'Qual é o nome de um animal mamífero?',
        categoria: 'Zoologia',
        alternativas: [
          'Cavalo', 'Vaca', 'Gato', 'Cachorro', 'Girafa', 'Elefante',
          'Orangotango', 'Morcego', 'Baleia', 'Golfinho', 'Tatu', 'Capivara',
          'Galo', 'Pinguim', 'Serpente', 'Jacaré', 'Tartaruga', 'Toupeira',
          'Ouriço', 'Canguru', 'Coala', 'Panda', 'Camelo', 'Lhama',
          'Alce', 'Carneiro', 'Cabra', 'Lebre', 'Castor', 'Lontra', 'Doninha', 'Mico-leão',
          'Leão', 'Tigre', 'Cervo', 'Macaco', 'Rato', 'Preguiça', 'Tamanduá', 'Rinoceronte',
          'Guepardo', 'Hipopótamo', 'Lobo-guará',
        ],
      },
      {
        slug: 'orgao-do-corpo-humano',
        enunciado: 'Qual é o nome de um órgão do corpo humano?',
        categoria: 'Anatomia',
        alternativas: [
          'Coração', 'Pulmão', 'Fígado', 'Rim', 'Cérebro', 'Estômago',
          'Intestino', 'Pâncreas', 'Baço', 'Tireoide', 'Ovário', 'Testículo',
          'Vesícula biliar', 'Adrenal', 'Hipófise', 'Ureter', 'Bexiga',
          'Vaso sanguíneo', 'Artéria', 'Veia', 'Alvéolo', 'Medula óssea',
          'Nervo', 'Glândula', 'Lírio',
          'Intestino grosso', 'Narina', 'Válvula',
        ],
      },
      {
        slug: 'camada-da-atmosfera',
        enunciado: 'Qual é o nome de uma camada da atmosfera terrestre?',
        categoria: 'Ecologia',
        alternativas: [
          'Troposfera', 'Estratosfera', 'Mesosfera', 'Termosfera', 'Exosfera',
          'Ionosfera', 'Magnetosfera', 'Ozoniosfera', 'Tropause', 'Estratopause',
          'Mesopause', 'Termopause', 'Exobase', 'Cúspide', 'Camada de ozônio',
          'Camada de inversão', 'Estratosfera polar', 'Camada de El Niño',
          'Camada de Jones', 'Camada de Chapman', 'Camada de Halley',
          'Camada de Kennelly', 'Camada de Heaviside',
          'Tropopausa', 'Estratopausa', 'Mesopausa', 'Termopausa', 'Aeropausa',
        ],
      },
      {
        slug: 'cientista-biologo',
        enunciado: 'Qual é o nome de um cientista conhecido por seus estudos em biologia?',
        categoria: 'História da ciência',
        alternativas: [
          'Charles Darwin', 'Gregor Mendel', 'Alfred Wallace', 'Jean-Baptiste Lamarck',
          'Carl von Linné', 'Louis Pasteur', 'Robert Koch', 'Alexander Fleming',
          'Barbara McClintock', 'Watson', 'Watson e Crick', 'J Watson',
          'J. D. Watson', 'Francis Crick', 'Theodosius Dobzhansky', 'Ernst Mayr',
          'Santiago Ramón y Cajal', 'Camillo Golgi', 'Jane Goodall',
          'Dian Fossey', 'Margaret Mead', 'Rachel Carson', 'James Watson',
          'James Dewey Watson', 'Fleming e Penicilina',
          'Darwin', 'Mendel', 'Pasteur', 'Koch', 'Lamarck', 'Linné', 'Fleming', 'Goodall',
          'Wallace', 'Carson',
        ],
      },
    ],
  },
  {
    slug: 'fisica',
    nome: 'Física',
    descricao: 'Grandezas, forças, luz e movimento.',
    questoes: [
      {
        slug: 'grandeza-fisica',
        enunciado: 'Qual é o nome de uma grandeza física?',
        categoria: 'Grandezas',
        alternativas: [
          'Massa', 'Comprimento', 'Tempo', 'Temperatura', 'Velocidade',
          'Aceleração', 'Força', 'Energia', 'Potência', 'Pressão',
          'Corrente elétrica', 'Resistência', 'Carga elétrica', 'Trabalho',
          'Quantidade de movimento', 'Frequência', 'Amplitude', 'Densidade',
          'Torque', 'Tensão', 'Carga', 'Momento angular', 'Impedância',
          'Fluxo',
          'Corrente', 'Deslocamento',
        ],
      },
      {
        slug: 'unidade-do-si',
        enunciado: 'Qual é o nome de uma unidade do Sistema Internacional?',
        categoria: 'Grandezas',
        alternativas: [
          'Metro', 'Quilograma', 'Segundo', 'Ampere', 'Kelvin', 'Mol',
          'Candela', 'Newton', 'Joule', 'Watt', 'Pascal', 'Hertz', 'Volt',
          'Ohm', 'Siemens', 'Tesla', 'Weber', 'Farad', 'Henry', 'Becquerel',
          'Gray', 'Coulomb', 'Lux', 'Radian', 'Esterel',
          'Angstrom', 'Decibel', 'Grau',
        ],
      },
      {
        slug: 'fenomeno-da-optica',
        enunciado: 'Qual é o nome de um fenômeno da óptica?',
        categoria: 'Óptica',
        alternativas: [
          'Reflexão', 'Refração', 'Difração', 'Interferência', 'Dispersão',
          'Polarização', 'Absorção', 'Transmissão', 'Espelhamento',
          'Difusão', 'Colisão de fótons', 'Aberração', 'Compton', 'Efeito Doppler',
          'Efeito Fotoelétrico', 'Espalhamento Rayleigh', 'Reflexão total',
          'Aberração cromática', 'Cegueira noturna', 'Contraste', 'Brilho especular',
          'Arco-íris', 'Reflexo', 'Espectro', 'Miragem',
        ],
      },
      {
        slug: 'cientista-fisico',
        enunciado: 'Qual é o nome de um físico conhecido por suas contribuições?',
        categoria: 'História da ciência',
        alternativas: [
          'Isaac Newton', 'Albert Einstein', 'Galileu Galilei', 'Isaac Hooke',
          'Niels Bohr', 'Max Planck', 'Michael Faraday', 'Nikola Tesla',
          'James Clerk Maxwell', 'William Thomson', 'J. J. Thomson',
          'Ernest Rutherford', 'Enrico Fermi', 'Werner Heisenberg',
          'Wolfgang Pauli', 'Louis de Broglie', 'Marie Curie', 'Pierre Curie',
          'Heike Kamerlingh Onnes', 'Hendrik Lorentz', 'Hendrik',
          'Robert Hooke', 'Evangelista Torricelli', 'Leon Foucault',
          'Alessandro Volta', 'André-Marie Ampère', 'Georg Ohm',
          'Einstein', 'Newton', 'Galileu', 'Faraday', 'Curie', 'Bohr', 'Planck', 'Rutherford',
          'Ampère', 'Volta', 'Ohm', 'Torricelli',
        ],
      },
      {
        slug: 'tipo-de-energia',
        enunciado: 'Qual é o nome de um tipo de energia?',
        categoria: 'Termodinâmica',
        alternativas: [
          'Energia cinética', 'Energia potencial', 'Energia térmica',
          'Energia química', 'Energia nuclear', 'Energia elétrica',
          'Energia luminosa', 'Energia sonora', 'Energia solar', 'Energia eólica',
          'Energia potencial gravitacional', 'Energia magnética',
          'Energia elástica', 'Energia química nuclear', 'Energia geotérmica',
          'Energia mareomotriz', 'Energia biomassa', 'Energia hidrelétrica',
          'Energia mecânica', 'Energia interna', 'Energia das marés', 'Energia rotacional', 'Energia de pressão',         ],
      },
    ],
  },
  {
    slug: 'historia',
    nome: 'História',
    descricao: 'Brasil e mundo: datas, pessoas e processos.',
    questoes: [
      {
        slug: 'presidente-do-brasil',
        enunciado: 'Qual é o nome de um presidente do Brasil?',
        categoria: 'Brasil',
        alternativas: [
          'Getúlio Vargas', 'Juscelino Kubitschek', 'João Goulart', 'Jânio Quadros',
          'Fernando Collor', 'Luiz Inácio Lula da Silva', 'Dilma Rousseff',
          'Michel Temer', 'Jair Bolsonaro', 'Deodoro da Fonseca',
          'Floriano Peixoto', 'Prudente de Morais', 'Campos Sales',
          'Rodrigues Alves', 'Nilo Peçanha', 'Epitácio Pessoa',
          'Artur Bernardes', 'Washington Luís', 'Café Filho', 'Carlos Luz',
          'Nereu Ramos', 'Castelo Branco', 'Costa e Silva', 'Emílio Médici',
          'Ernesto Geisel', 'João Figueiredo', 'Tancredo Neves', 'José Sarney',
          'Itamar Franco', 'Fernando Henrique Cardoso', 'Lula da Silva', 'Marcelo', 'Alckmin', 'Sarney', 'FHC',
          'Juscelino', 'Goulart', 'Collor', 'Temer', 'Bolsonaro',
          'Calor', 'Fotovoltaica', 'Termoelétrica',
          'Lula', 'Tancredo', 'Fernando Henrique', 'Getúlio', 'Vargas', 'Jânio', 'Quadros',
          'Kubitschek', 'Rousseff', 'Itamar', 'Bernardes', 'Floriano',
        ],
      },
      {
        slug: 'lei-historica',
        enunciado: 'Qual é o nome de uma lei histórica do Brasil?',
        categoria: 'Brasil',
        alternativas: [
          'Lei Áurea', 'Lei do Ventre Livre', 'Lei dos Sexentários',
          'Lei Eusébio de Queirós', 'Lei Feijó', 'Lei de Ancine',
          'Lei Rouanet', 'Lei Maria da Penha',
          'Lei de Tortura', 'Lei Seca',
          'Lei Corges',
          'Lei Eloi', 'Lei de Cotas', 'Lei de Curriculum',
          'Lei Tarjf', 'Lei de Combate à Fome',
          'Lei de Propriedade Industrial', 'Lei Antônio', 'Lei orgânica',
          'Lei Complementar', 'Emenda Constitucional',
          'Lei Falimentária', 'Lei de Drogas', 'Lei dos Anos de Chumbo',
        ],
      },
      {
        slug: 'conflito-historico',
        enunciado: 'Qual é o nome de um conflito ou movimento histórico brasileiro?',
        categoria: 'Brasil',
        alternativas: [
          'Guerra de Contestado', 'Guerra dos Canudos', 'Inconfidência Mineira',
          'Conspiração Mineira', 'Guerra do Paraguai', 'Guerra do Acre',
          'Revolução de 1930', 'Revolução de 1932', 'Revolução Constitucionalista',
          'Intentona Comunista', 'Revolta da Armada', 'Inconfidência da Bahia', 'Cabanagem',
          'Guerra dos Farrapos', 'Revolta do Contestado', 'Rebelião Nativista',
          'Levante de 1893', 'Revolta Prestes', 'Revolução de 1891', 'Quebra-Quilos', 'Revolta do Formoso',
          'Guerra do Contestado', 'Canudos', 'Inconfidência', 'Paraguai', 'Acre', 'Farrapos',
          'Intentona',
        ],
      },
      {
        slug: 'cidade-historica',
        enunciado: 'Qual é o nome de uma cidade histórica do Brasil?',
        categoria: 'Brasil',
        alternativas: [
          'Salvador', 'Olinda', 'Ouro Preto', 'Mariana', 'São Luís',
          'Tiradentes', 'Goiás', 'São João del-Rei', 'Paraty', 'Ilhéus',
          'Porto Seguro', 'Recife', 'Natal', 'João Pessoa', 'Fortaleza',
          'Belém', 'São Luís do Maranhão', 'Diamantina', 'Congonhas',
          'São José del-Rei', 'Ipiranga', 'Santos', 'Angra dos Reis',
          'Vila Velha', 'Alcântara', 'Carolina', 'Petrópolis', 'Blumenau',
          'São Paulo', 'Rio de Janeiro', 'Vitória', 'Cuiabá',
        ],
      },
      {
        slug: 'civilizacao-antiga',
        enunciado: 'Qual é o nome de uma civilização da Antiguidade?',
        categoria: 'Mundo',
        alternativas: [
          'Egípcios', 'Romanos', 'Gregos', 'Maias', 'Astecas', 'Incas',
          'Vikings', 'Fenícios', 'Persas', 'Turcos', 'Sumérios',
          'Babilônios', 'Assírios', 'Hititas', 'Cretenses', 'Espartanos',
          'Cartagineses', 'Etíopes', 'Olmecas', 'Ninivitas', 'Judeus',
          'Celtas', 'Sáxões', 'Normandos', 'Macedônios', 'Gálatas',
          'Indianos', 'Chineses',
          'Sumerianos',
        ],
      },
    ],
  },
  {
    slug: 'ingles',
    nome: 'Inglês',
    descricao: 'Vocabulário, dias, meses e substantivos.',
    questoes: [
      {
        slug: 'animal-domestico-em-ingles',
        enunciado: 'Qual é o nome de um animal doméstico em inglês?',
        categoria: 'Vocabulário',
        alternativas: [
          'Dog', 'Cat', 'Cow', 'Horse', 'Sheep', 'Goat', 'Pig', 'Chicken',
          'Duck', 'Rabbit', 'Donkey', 'Hamster', 'Parrot', 'Turtle', 'Mouse',
          'Rat', 'Llama', 'Alpaca', 'Frog', 'Bee', 'Camel', 'Ferret',
          'Guinea pig', 'Canary', 'Goldfish', 'Parakeet', 'Goose',
          'Turkey', 'Squirrel', 'Hedgehog',
          'Kitten', 'Puppy', 'Bull', 'Ox', 'Lamb', 'Calf', 'Pony',
        ],
      },
      {
        slug: 'cor-em-ingles',
        enunciado: 'Qual é o nome de uma cor em inglês?',
        categoria: 'Vocabulário',
        alternativas: [
          'Red', 'Blue', 'Green', 'Yellow', 'Black', 'White', 'Orange',
          'Purple', 'Pink', 'Brown', 'Grey', 'Gray', 'Violet', 'Gold',
          'Silver', 'Beige', 'Turquoise', 'Magenta', 'Navy', 'Crimson',
          'Indigo', 'Maroon', 'Olive', 'Ivory', 'Lilac', 'Peach',
          'Scarlet', 'Amber', 'Chartreuse', 'Fuchsia', 'Salmon',
          'Burgundy', 'Lavender',
          'Teal', 'Cyan', 'Khaki', 'Aquamarine',
        ],
      },
      {
        slug: 'mes-em-ingles',
        enunciado: 'Qual é o nome de um mês do ano em inglês?',
        categoria: 'Calendário',
        alternativas: [
          'January', 'February', 'March', 'April', 'May', 'June', 'July',
          'August', 'September', 'October', 'November', 'December',
          'Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho',
          'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro',
          'Jan', 'Feb', 'Mar', 'Apr', 'Jun', 'Jul', 'Aug', 'Sep',
          'Oct', 'Nov', 'Dec',
          'Sept',
        ],
      },
      {
        slug: 'fruta-em-ingles',
        enunciado: 'Qual é o nome de uma fruta em inglês?',
        categoria: 'Vocabulário',
        alternativas: [
          'Apple', 'Banana', 'Orange', 'Grape', 'Lemon', 'Strawberry',
          'Watermelon', 'Pineapple', 'Mango', 'Peach', 'Pear', 'Cherry',
          'Kiwi', 'Papaya', 'Melon', 'Lime', 'Apricot', 'Fig', 'Plum',
          'Coconut', 'Raspberry', 'Blueberry', 'Blackberry', 'Guava',
          'Persimmon', 'Tangerine', 'Mandarin', 'Pomegranate', 'Date',
          'Avocado', 'Cashew',
          'Cranberry', 'Lychee', 'Nectarine', 'Rambutan', 'Tamarind',
        ],
      },
      {
        slug: 'esporte-em-ingles',
        enunciado: 'Qual é o nome de um esporte em inglês?',
        categoria: 'Vocabulário',
        alternativas: [
          'Football', 'Soccer', 'Basketball', 'Volleyball', 'Tennis',
          'Swimming', 'Running', 'Cycling', 'Golf', 'Hockey', 'Rugby',
          'Baseball', 'Boxing', 'Judo', 'Karate', 'Wrestling', 'Skiing', 'Skating', 'Surfing', 'Rowing', 'Diving', 'Climbing',
          'Athletics', 'Handball', 'Badminton', 'Curling', 'Archery',
          'Fencing', 'Taekwondo', 'Polo', 'Cricket', 'Bowling', 'Sailing',
          'Skateboarding', 'Snowboarding', 'Surf', 'Skate', 'Darts',
        ],
      },
    ],
  },
  {
    slug: 'matematica',
    nome: 'Matemática',
    descricao: 'Números, figuras e operações.',
    questoes: [
      {
        slug: 'operacao-matematica',
        enunciado: 'Qual é o nome de uma operação matemática?',
        categoria: 'Aritmética',
        alternativas: [
          'Adição', 'Subtração', 'Multiplicação', 'Divisão', 'Potenciação',
          'Potencia', 'Radiciação', 'Raiz quadrada', 'Raiz cúbica', 'Módulo',
          'Fatorial', 'Logaritmo', 'Seno', 'Cosseno', 'Tangente',
          'Arredondamento', 'Simplificação', 'Fatoração', 'Expansão',
          'Percentual', 'Proporção', 'Escala', 'Derivação', 'Integração',
          'Somatório', 'Produtório',
          'Soma', 'Raiz', 'Porcentagem', 'Resto',
        ],
      },
      {
        slug: 'figura-geometrica',
        enunciado: 'Qual é o nome de uma figura geométrica?',
        categoria: 'Geometria',
        alternativas: [
          'Círculo', 'Triângulo', 'Quadrado', 'Retângulo', 'Pentágono',
          'Hexágono', 'Losango', 'Trapézio', 'Oval', 'Paralelogramo',
          'Polígono', 'Cilindro', 'Cone', 'Esfera', 'Cubo', 'Pirâmide',
          'Circunferência', 'Corda', 'Setor', 'Arco', 'Semicírculo',
          'Prisma', 'Tronco de pirâmide', 'Torus', 'Elipse', 'Hipérbole',
          'Parábola', 'Assoalhada',
          'Estrela', 'Rombo', 'Cruz',
        ],
      },
      {
        slug: 'numero-primo',
        enunciado: 'Qual é um número primo?',
        categoria: 'Números',
        alternativas: [
          '2', '3', '5', '7', '11', '13', '17', '19', '23', '29',
          '31', '37', '41', '43', '47', '53', '59', '61', '67', '71',
          '73', '79', '83', '89', '97', '101', '103', '107', '109', '113',
          '127', '131', '137', '139', '149', '151', '157', '163', '167', '173',
        ],
      },
      {
        slug: 'tipo-de-grafico',
        enunciado: 'Qual é o nome de um tipo de gráfico?',
        categoria: 'Estatística',
        alternativas: [
          'Gráfico de pizza', 'Gráfico de barras', 'Gráfico de linhas',
          'Gráfico de área', 'Gráfico de dispersão', 'Histograma',
          'Gráfico de radar', 'Gráfico de rosca', 'Diagrama de caixa',
          'Gráfico de funil', 'Diagrama de Sankey', 'Gráfico de colunas',
          'Gráfico circular', 'Gráfico de barras horizontais',
          'Gráfico de compounded', 'Gráfico de Candlestick', 'Gráfico OHLC',
          'Treemap', 'Dendrograma', 'Heatmap', 'Boxplot',
          'Gráfico de strip plot', 'Violin plot', 'Diagrama de Venn',
          'Pareto', 'Diagrama de causas', 'Fluxograma',
          'Gráfico de bolhas', 'Waterfall', 'Gantt', 'Sunburst',
        ],
      },
      {
        slug: 'sequencia-numerica',
        enunciado: 'Qual é o nome de uma sequência numérica conhecida?',
        categoria: 'Números',
        alternativas: [
          'Fibonacci', 'Progressão aritmética', 'Progressão geométrica',
          'Números primos', 'Números de Fibonacci', 'Sequência de Pells',
          'Números de Catalan', 'Números de Lucas', 'Números de Bell',
          'Números de Stirling', 'Triangulares', 'Quadrados perfeitos',
          'Números quadrados', 'Sequência tribonacci', 'Progressão harmônica', 'Sequência de Ramanujan', 'Números de Collatz',
          'Sequência de Sylow', 'Números de Motzkin', 'Sequência de Somos',
          'Números de Pell-Lucas', 'Sequência Jacobsthal', 'Números de Euclid',
          'Pell', 'Catalan', 'Tribonacci', 'Sylvester',
        ],
      },
    ],
  },
  {
    slug: 'portugues',
    nome: 'Português',
    descricao: 'Gramática, semântica e uso da língua.',
    questoes: [
      {
        slug: 'figura-de-linguagem',
        enunciado: 'Qual é o nome de uma figura de linguagem?',
        categoria: 'Semântica',
        alternativas: [
          'Metáfora', 'Metonímia', 'Hipérbole', 'Eufemismo', 'Ironia',
          'Antítese', 'Paradoxo', 'Pleonasmo', 'Tautologia', 'Aliteração',
          'Anáfora', 'Epíteto', 'Prosopopeia', 'Polissíndeto', 'Zeugma',
          'Onomatopeia', 'Silepse', 'Ambiguidade', 'Sinestesia', 'Enumeração',
          'Gradação', 'Apóstrofo', 'Parêntese', 'Antífrase', 'Metaplan',
          'Blason', 'Hiperbaton', 'Ironia verbal', 'Meonímia',
          'Personificação', 'Paronomásia', 'Delipse',
        ],
      },
      {
        slug: 'tipo-de-oracao',
        enunciado: 'Qual é o nome de um tipo de oração da língua portuguesa?',
        categoria: 'Sintaxe',
        alternativas: [
          'Oração declarativa', 'Oração interrogativa', 'Oração exclamativa',
          'Oração imperativa', 'Oração optativa', 'Oração oracional',
          'Oração subordinada', 'Oração principal',
          'Oração subordinada substantiva', 'Oração subordinada adjetiva',
          'Oração subordinada adverbial', 'Oração coordenada',
          'Oração indireta', 'Oração direta', 'Oração relativa', 'Oração causal',
          'Oração final', 'Oração condicional', 'Oração concessiva',
          'Oração conformativa', 'Oração comparativa', 'Oração consecutiva',
          'Oração proporcional',
          'Oração dubitativa', 'Oração desiderativa',
        ],
      },
      {
        slug: 'conectivo-do-portugues',
        enunciado: 'Qual é o nome de um conectivo usado em português?',
        categoria: 'Conectivos',
        alternativas: [
          'Mas', 'Porém', 'Portanto', 'Pois', 'Porque', 'Embora', 'Se',
          'Caso', 'Quando', 'Enquanto', 'Logo', 'Então', 'Além disso',
          'Por exemplo', 'Isto é', 'Ou seja', 'Todavia', 'Contudo',
          'Entretanto', 'Consequentemente', 'Por conseguinte', 'Assim',
          'Posto que', 'Uma vez que', 'Já que', 'Visto que', 'De modo que',
          'Por outro lado', 'Ademais', 'Por fim', 'Noutro modo',
          'Em contrapartida', 'Por sua vez', 'Aliás', 'Inclusive', 'Por sinal', 'De qualquer modo',
          'Ou', 'Nem', 'Ainda', 'Afinal',
        ],
      },
      {
        slug: 'tipo-de-texto',
        enunciado: 'Qual é o nome de um tipo de texto?',
        categoria: 'Gênero textual',
        alternativas: [
          'Narrativo', 'Descritivo', 'Argumentativo', 'Expositivo',
          'Injuntivo', 'Dissertativo', 'Informativo', 'Jornalístico',
          'Publicitário', 'Entrevista', 'Reportagem', 'Crônica',
          'Artigo de opinião', 'Ensaio', 'Memorial', 'Conto', 'Novela',
          'Crônica esportiva', 'Notícia', 'Editorial', 'Carta',
          'Diário', 'Poema', 'Lenda', 'Fábula', 'Receita',
          'Relato', 'Relatório', 'Artigo',
        ],
      },
      {
        slug: 'parte-do-discurso',
        enunciado: 'Qual é o nome de uma parte do discurso?',
        categoria: 'Gramática',
        alternativas: [
          'Substantivo', 'Adjetivo', 'Verbo', 'Advérbio', 'Preposição',
          'Conjunção', 'Artigo', 'Numeral', 'Pronome', 'Interjeição',
          'Locução', 'Conectivo', 'Determinante', 'Quantificador',
          'Afixo', 'Radical', 'Sílaba', 'Fonema', 'Grafema', 'Morfema', 'Pedúnculo',
          'Predicado', 'Sujeito', 'Objeto direto', 'Objeto indireto', 'Vocativo',
        ],
      },
    ],
  },
  {
    slug: 'quimica',
    nome: 'Química',
    descricao: 'Elementos, estruturas, soluções e reações.',
    questoes: [
      {
        slug: 'elemento-quimico',
        enunciado: 'Qual é o nome de um elemento químico?',
        categoria: 'Tabela periódica',
        alternativas: [
          'Hidrogênio', 'Hélio', 'Carbono', 'Nitrogênio', 'Oxigênio',
          'Enxofre', 'Ferro', 'Cobre', 'Zinco', 'Ouro', 'Prata', 'Chumbo',
          'Alumínio', 'Silício', 'Fósforo', 'Cloro', 'Bromo', 'Iodo',
          'Lítio', 'Sódio', 'Magnésio', 'Potássio', 'Cálcio', 'Titânio',
          'Cobalto', 'Níquel', 'Cromo', 'Manganês', 'Mercúrio', 'Uranio',
          'Plutônio', 'Tântalo', 'Índio', 'Berílio',
          'Flúor', 'Estanho', 'Bário', 'Boro', 'Césio',
        ],
      },
      {
        slug: 'propriedade-da-materia',
        enunciado: 'Qual é o nome de uma propriedade da matéria?',
        categoria: 'Propriedades',
        alternativas: [
          'Massa', 'Volume', 'Densidade', 'Ponto de fusão',
          'Ponto de ebulição', 'Solubilidade', 'Cor', 'Odor', 'Dureza',
          'Condutividade elétrica', 'Reatividade', 'Radioatividade',
          'Viscosidade', 'Tensão superficial', 'Elasticidade',
          'Compressibilidade', 'Dilatação térmica', 'Calor específico',
          'Condutividade térmica', 'Adsorção', 'Absorção', 'Refração da luz', 'Opacidade', 'Brilho', 'Polarização da luz',
          'Reatividade química',
          'Porosidade', 'Turbidez', 'Abrasividade',
        ],
      },
      {
        slug: 'reacao-quimica',
        enunciado: 'Qual é o nome de uma reação química?',
        categoria: 'Reações',
        alternativas: [
          'Síntese', 'Decomposição', 'Combustão', 'Oxidação', 'Redução',
          'Neutralização', 'Precipitação', 'Fotossíntese', 'Fermentação',
          'Corrosão', 'Eletrólise', 'Saponificação', 'Polimerização',
          'Ciclização', 'Condensação', 'Substituição', 'Adição',
          'Dupla troca', 'Reação de neutralização', 'Reação de neutralização ácido-base',
          'Calcinação', 'Pirólise', 'Hidrogenação', 'Amidação',
          'Reação de Cannizzaro', 'Reação de Wurtz', 'Reação de Grignard',
          'Incrustação', 'Combustão completa', 'Oxidação completa',
        ],
      },
      {
        slug: 'acido-quimico',
        enunciado: 'Qual é o nome de um ácido químico?',
        categoria: 'Ácidos',
        alternativas: [
          'Ácido sulfúrico', 'Ácido clorídrico', 'Ácido nítrico',
          'Ácido acético', 'Ácido cítrico', 'Ácido lático',
          'Ácido carbônico', 'Ácido fosfórico', 'Ácido bromídrico',
          'Ácido iodídrico', 'Ácido sulfídrico', 'Ácido butírico',
          'Ácido benzoico', 'Ácido oleico', 'Ácido láurico',
          'Ácido palmítico', 'Ácido esteárico', 'Ácido tartárico',
          'Ácido málico', 'Ácido úrico', 'Ácido oxálico',
          'Ácido pirúvico', 'Ácido glutâmico', 'Ácido aspártico',
          'Ácido muriático', 'Ácido hipocloroso', 'Ácido fluorídrico', 'Ácido bórico',
        ],
      },
      {
        slug: 'instrumento-de-laboratorio',
        enunciado: 'Qual é o nome de um instrumento de laboratório químico?',
        categoria: 'Laboratório',
        alternativas: [
          'Bico de Bunsen', 'Béquer', 'Proveta', 'Erlenmeyer', 'Balão de vidro',
          'Estufa', 'Mufla', 'Centrífuga', 'pHmetro', 'Microscópio',
          'Bureta', 'Pipeta', 'Termômetro', 'Funil de Büchner', 'Cadinho',
          'Cuba', 'Picnômetro', 'Dessecador', 'Papel de filtro', 'Capilar',
          'Bastão de vidro', 'Tubo de ensaio', 'Espátula', 'Pinça',
          'Suporte de anel', 'Cilindro graduado', 'Pipetador',
          'Tripé', 'Balão', 'Funil', 'Matraz',
        ],
      },
    ],
  },
]
